### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by morganekmefjord** [leanaiorg/leanaistack#1]
![65325764-02403480-dbb0-11e9-9b82-6501bbacb999](https://user-images.githubusercontent.com/2098408/65333320-91eddf00-dbc0-11e9-8bfb-3c9774b62af2.png)

![SO Outline Flat](https://user-images.githubusercontent.com/2098408/65333699-42f47980-dbc1-11e9-9db3-f0e5dcdadc8b.png)

**Comment by olas** [comment]
![uu_logo](https://user-images.githubusercontent.com/46811/65514444-9b878780-dedd-11e9-8bb4-87566100c274.png)
![pharmbio-logo](https://user-images.githubusercontent.com/46811/65514461-a04c3b80-dedd-11e9-876a-cb6a797f8ab7.png)

**Comment by olas** [comment]
![uu_logo](https://user-images.githubusercontent.com/46811/65514759-439d5080-dede-11e9-8389-b22cffffd892.png)
![pharmbio-logo](https://user-images.githubusercontent.com/46811/65514764-46984100-dede-11e9-9c1d-834d11b82816.png)
